---

#- name: git clone vivisect
#  git:
#    repo=https://github.com/fireeye/flare-vivisect.git
#    dest={{ toolsetdir }}/vivisect
#    version={{ vivisect_version }}

- block:
    - name: python dependencies
      package: name={{ item }} state=present
      with_items: "{{ vivisect_deps }}"
    - name: install vivisect with pip
      pip:
        name: "{{ vivisect_pip_module }}"
        state: present
        executable: "{{ vivisect_pip }}"
  when: vivisect_virtualenv_path is not defined or vivisect_virtualenv_path == ''

- block:
    - name: virtualenv dependencies
      package: name={{ item }} state=present
      with_items: "{{ vivisect_deps + [ vivisect_virtualenv ] }}"
    - name: ensure virtualenv user {{ vivisect_virtualenv_user }} exists
      user: "name={{ vivisect_virtualenv_user }} home={{ vivisect_virtualenv_home }} state=present"

    - name: Trusty+Centos7 | install vivisect python bindings - virtualenv
      pip:
        name: "{{ vivisect_pip_module }}"
        state: present
        virtualenv: "{{ vivisect_virtualenv_path }}"
        executable: "{{ vivisect_pip }}"
      become: yes
      become_user: "{{ vivisect_virtualenv_user }}"
      when: (ansible_distribution_release == 'trusty' and vivisect_pip == 'pip3') or (ansible_os_family == "RedHat" and ansible_distribution_version.split('.')[0] == '7')

    - name: Other | install vivisect python bindings - virtualenv
      pip:
        name: "{{ vivisect_pip_module }}"
        state: present
        virtualenv: "{{ vivisect_virtualenv_path }}"
        virtualenv_command: "{{ vivisect_vcommand }}"
## FIXME! end with owner root
      become: yes
      become_user: "{{ vivisect_virtualenv_user }}"
      when: not (ansible_distribution_release == 'trusty' and vivisect_pip == 'pip3')
## FIXME! not idempotent
#    - name: ensure right permissions
#      file: "dest={{ vivisect_virtualenv_path }} state=directory owner={{ vivisect_virtualenv_user }} recurse=yes"
  when: vivisect_virtualenv_path is defined and vivisect_virtualenv_path != ''

