---

- name: Converge
  hosts: all
  environment:
    http_proxy: "{{ lookup('env', 'http_proxy') }}"
    https_proxy: "{{ lookup('env', 'https_proxy') }}"
    no_proxy: "{{ lookup('env', 'no_proxy') }}"
  remote_user: root
  pre_tasks:
    - name: Ubuntu | Install python3
      ansible.builtin.raw: test -e /usr/bin/python3 || (apt -y update && apt install -y python3-minimal python3-setuptools)
      register: python3
      changed_when: "'installed' in python3.stdout"
      when: (ansible_facts['distribution'] == "Ubuntu" and ansible_facts['distribution_major_version'] | int >= 16)
    - name: RedHat | Install python3
      ansible.builtin.raw: test -e /usr/bin/python3 || (yum install -y python3)
      register: python3
      changed_when: "'installed' in python3.stdout"
      when: (ansible_facts['os_family'] == "RedHat" and ansible_facts['distribution_major_version'] | int >= 7)
    - name: Gather Facts
      ansible.builtin.setup:
      when: (ansible_facts['distribution'] == "Ubuntu" and ansible_facts['distribution_major_version'] | int >= 16)
    - name: Debian | Refresh apt cache
      ansible.builtin.apt:
        update_cache: yes
        cache_valid_time: 3600
      when: ansible_facts['os_family'] == "Debian"
    - name: Ubuntu Bionic+, Redhat 7+ | Enforce python3 for ansible
      ansible.builtin.set_fact:
        ansible_python_interpreter: /usr/bin/python3
      when: >
        (ansible_facts['distribution'] == "Ubuntu" and ansible_facts['distribution_major_version'] | int >= 16) or
        (ansible_facts['os_family'] == "RedHat" and ansible_facts['distribution_major_version'] | int >= 7)
    - name: Ubuntu Focal | Enforce python3 as only one
      ansible.builtin.set_fact:
        vivisect_pip: pip3
        vivisect_vcommand: virtualenv3
        vivisect_python: python3
        vivisect_deps:
          - python3
          - python3-pip
        vivisect_virtualenv:
          - python3-virtualenv
      when: >
        (ansible_facts['distribution'] == "Ubuntu" and ansible_facts['distribution_major_version'] | int >= 20)
    - name: Redhat 8+ | Enforce python3
      ansible.builtin.set_fact:
        vivisect_pip: pip3
        vivisect_vcommand: virtualenv-3
        vivisect_python: python3
        vivisect_deps:
          - python3
          - python3-pip
        vivisect_virtualenv: python3-virtualenv
      when: >
        (ansible_facts['os_family'] == "RedHat" and ansible_facts['distribution_major_version'] | int >= 8)
  roles:
    - juju4.vivisect
