---

- name: Converge
  hosts: all
  environment:
    http_proxy: "{{ lookup('env', 'http_proxy') }}"
    https_proxy: "{{ lookup('env', 'https_proxy') }}"
    no_proxy: "{{ lookup('env', 'no_proxy') }}"
  remote_user: root
  pre_tasks:
    - name: Ubuntu | Install python3
      raw: test -e /usr/bin/python3 || (apt -y update && apt install -y python3-minimal python3-setuptools)
      register: python3
      changed_when: "'installed' in python3.stdout"
      when: (ansible_distribution == "Ubuntu" and ansible_distribution_major_version|int >= 16)
    - name: RedHat | Install python3
      raw: test -e /usr/bin/python3 || (yum install -y python3)
      register: python3
      changed_when: "'installed' in python3.stdout"
      when: (ansible_os_family == "RedHat" and ansible_distribution_major_version|int >= 8)
    - name: Gather Facts
      setup:
      when: (ansible_distribution == "Ubuntu" and ansible_distribution_major_version|int >= 16)
    - name: Ubuntu Bionic+, Redhat 7+ | Enforce python3 for ansible
      set_fact:
        ansible_python_interpreter: /usr/bin/python3
      when: >
        (ansible_distribution == "Ubuntu" and ansible_distribution_major_version|int >= 16) or
        (ansible_os_family == "RedHat" and ansible_distribution_major_version|int >= 7)
    - name: Ubuntu Focal | Enforce python3 as only one
      set_fact:
        vivisect_pip: pip3
        vivisect_vcommand: virtualenv3
        vivisect_python: python3
        vivisect_deps:
          - python3
          - python3-pip
        vivisect_virtualenv:
          - python3-virtualenv
      when: >
        (ansible_distribution == "Ubuntu" and ansible_distribution_major_version|int >= 20)
    - name: Redhat 8+ | Enforce python3
      set_fact:
        vivisect_pip: pip3
        vivisect_vcommand: virtualenv-3
        vivisect_python: python3
        vivisect_deps:
          - python3
          - python3-pip
        vivisect_virtualenv: python3-virtualenv
      when: >
        (ansible_os_family == "RedHat" and ansible_distribution_major_version|int >= 8)
  roles:
    - juju4.vivisect
