---

- name: Verify
  hosts: vivi
  pre_tasks:
    - name: Ubuntu Bionic+ | Enforce python3
      set_fact:
        vivisect_pip: pip3
      when: >
        (ansible_distribution == "Ubuntu" and ansible_distribution_major_version|int >= 18)
    - name: Redhat 7+ | Enforce python3
      set_fact:
        vivisect_pip: pip3
      when: >
        (ansible_os_family == "RedHat" and ansible_distribution_major_version|int >= 7)
  tasks:
    - name: Validate installed pip packages
      command: "{{ vivisect_pip }} freeze"
      changed_when: false
      register: pip
    - name: Validate pip
      assert:
        that: >
          "'vivisect' in pip.stdout"
